name: Build GrupoND Versions

on:
  workflow_dispatch:
    inputs:
      rs_server:
        description: 'Endereço do Servidor ID/Relay (ex: rustdesk.grupond.com.br)'
        required: true
        default: 'SEU_IP_OU_DOMINIO'

env:
  RUST_VERSION: "1.75"
  FLUTTER_VERSION: "3.24.5"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"

jobs:
  build-windows:
    name: Build Windows Versions
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        version: [client, admin]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set Environment Variables
        shell: pwsh
        run: |
          # Define VCPKG_ROOT based on runner's pre-installed path
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV
          
          if ("${{ matrix.version }}" -eq "client") {
            echo "APP_NAME=Atendimento GrupoND" >> $env:GITHUB_ENV
            echo "RS_INCOMING_ONLY=1" >> $env:GITHUB_ENV
            echo "RS_DISABLE_SETTINGS=1" >> $env:GITHUB_ENV
            echo "OUTPUT_NAME=Atendimento_GrupoND" >> $env:GITHUB_ENV
          } else {
            echo "APP_NAME=Admin GrupoND" >> $env:GITHUB_ENV
            echo "RS_HIDE_NETWORK=1" >> $env:GITHUB_ENV
            echo "OUTPUT_NAME=Admin_GrupoND" >> $env:GITHUB_ENV
          }
          echo "RS_SERVER=${{ github.event.inputs.rs_server }}" >> $env:GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: x86_64-pc-windows-msvc

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Install dependencies (vcpkg)
        shell: pwsh
        run: |
          vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static aom:x64-windows-static
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV

      - name: Build
        shell: pwsh
        run: |
          python build.py

      - name: Rename and Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: |
            target/release/*.exe
            flutter/build/windows/x64/runner/Release/*.exe
